set-window-option -g mode-keys vi

set -ag terminal-overrides ",screen-256color:colors=256:Tc:Ms=\\E]52;c;%p2%s\\7"
set -g set-clipboard on

set -g default-terminal "screen-256color"
set -g base-index 1
set -g pane-base-index 1
set -g mouse off

set-option -g status-position bottom
set-option -g renumber-windows on
set-option -g repeat-time 0

# Removes ESC delay
set -sg escape-time 0

# Bind copy mode to q key
bind q copy-mode

# Setup ` as the prefix
set-option -g prefix `
bind-key ` send-prefix

# Swaps the selected pane with the pane above it
bind u swap-pane -U

# Make a new pane 14 lines high, from the bottom
bind o splitw -f -l 14
#split-window -v -p 25

# Shift+left/right cycles through windows
bind-key -n S-right next
bind-key -n S-left prev

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
#set -g @plugin 'catppuccin/tmux#v2.1.2'
set -g @plugin 'wfxr/tmux-power'

#set -g @tpm_plugins '                     \
#    tmux-plugins/tpm                      \
#    tmux-plugins/tmux-sensible            \
#    tmux-plugins/tmux-resurrect           \
#    tmux-plugins/tmux-continuum           \
#    tmux-plugins/tmux-yank                \
#    tmux-plugins/tmux-pain-control        \
#    tmux-plugins/tmux-copycat             \
#    tmux-plugins/tmux-battery             \
#'


#   wfxr/tmux-power                       \
#    tmux-plugins/tmux-cpu                 \

#set -g @catppuccin_flavor "mocha"
#set -g @catppuccin_window_status_style "rounded"

#set -g @tmux_power_theme 'sky'
set -g @tmux_power_show_user    false
set -g @tmux_power_show_host    false
set -g @tmux_power_show_session false

#set -g @tmux_power_theme 'gold'
set -g @tmux_power_theme 'sky'
#set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
